name: Release, sonar scan
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

env:
  APPLICATION: persona
  GH_TOKEN_BOT: ${{ secrets.GH_TOKEN_BOT }}
  GH_ACTIONS_USER: ${{ secrets.GH_ACTIONS_USER }}

permissions:
  contents: read
  pull-requests: write
  id-token: write

concurrency:
  group: sonar-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Setup context
        uses: oakroots/setup-context@v1
        with:
          path: oakroots-actions

      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          repository: '${{ github.repository }}'
          token: ${{ secrets.GH_TOKEN_BOT }}
          path: ${{ github.repository }}
          fetch-depth: 0

      - name: Run tests
        uses: ./oakroots-actions/go-library-test
        with:
          working-directory: ${{ github.repository }}
          coverage: true

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ${{ github.repository }}/coverage.out

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: ${{ github.repository }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: Upload SonarQube Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonar-report-task
          path: ${{ github.repository }}/.scannerwork/report-task.txt

      - name: Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        with:
          scanMetadataReportFile: ${{ github.repository }}/.scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
